language: scala
sbt_args: "-J-Xmx2G"

notifications:
  email:
    false

before_script:
  - npm install

matrix:
  include:
  - env: SCALA_VERSION=2.13.1
    jdk: openjdk8
    script:
      - sbt ++$SCALA_VERSION clean test:compile
      - sbt ++$SCALA_VERSION test
      - sbt ++$SCALA_VERSION 'set scalaJSStage in Global := FullOptStage' test
  - env: SCALA_VERSION=2.12.10
    jdk: openjdk8
    script:
      - sbt ++$SCALA_VERSION clean test:compile
      - sbt ++$SCALA_VERSION test
      - sbt ++$SCALA_VERSION 'set scalaJSStage in Global := FullOptStage' test
      - sbt doc
      - grep -Eo "https?://[a-zA-Z0-9./?=_-]+" README.md | while read u; do echo $u; curl -LIs $u | grep "HTTP/1.1 200 OK\|HTTP/2.0 200\|HTTP/2 200" || exit 1; done

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
